# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    access_denied_url: /

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        our_users:
            entity: { class: AppBundle\Entity\User, property: email }
        fos_userbundle:
            id: fos_user.user_provider.username_email
        auth_token_user_provider:
            id: auth_token_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
            anonymous: ~

        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true
            access_denied_handler: AccessDeniedService
            logout_on_user_change: true
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_HELPER: ROLE_USER
        ROLE_COLLABORATOR: ROLE_MODERATOR
        ROLE_ORGANIZER: ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN

    access_control:
    - { path: ^/$, role: [ROLE_ORGANIZER,ROLE_HELPER, ROLE_SUPER_ADMIN, IS_AUTHENTICATED_ANONYMOUSLY] }
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/public, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, role: ROLE_SUPER_ADMIN }
    - { path: ^/organizer/raid/add$, role: [ROLE_ORGANIZER, ROLE_SUPER_ADMIN] }
    - { path: ^/organizer, role: [ROLE_ORGANIZER, ROLE_SUPER_ADMIN, ROLE_COLLABORATOR] }
    - { path: ^/helper/invite/, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/helper/register/, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/helper/join/, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/helper, role: [ROLE_HELPER, ROLE_SUPER_ADMIN] }
    - { path: ^/api/auth-tokens, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/profile, role: [ROLE_ORGANIZER,ROLE_HELPER,ROLE_COLLABORATOR] }
    - { path: ^/api/organizer, role: [ROLE_ORGANIZER, ROLE_COLLABORATOR] }
    - { path: ^/api/helper, role: ROLE_HELPER }
